### ISSUE TITLE
Menu trop long margot-fun si beaucoup d'entrées

### ISSUE THREAD

**Issue by J9rem** [YesWiki/yeswiki-theme-margot#15]
Avec margot-fun (v1.0.2), quand un menu possède de nombreuses entrées, il devient long et difficile à afficher.
Exemple : 
![image](https://user-images.githubusercontent.com/67152407/169480445-feb7610c-38c7-4c4c-81fa-7891b95cee92.png)

(il faut défiler toutes la pge pour voir tout le menu)

**Comment by J9rem** [comment]
Une solution non satisfaisante et d'ajouter ce bout de code css dans PageCSS mais ça ne me convient pas :
```css
#yw-topnav .dropdown-menu li {
  margin-bottom: .2rem;
}
#yw-topnav .links-container .nav a:not(.btn) {
  line-height: 1rem;
}
#yw-topnav .dropdown-menu a {
  padding: 3px 20px 3px 15px;
}
@media(max-width: 801px){
    #yw-topnav .navbar-nav > li > a {
       padding: 0.2rem 1rem !important;
    }
}
```

**Comment by J9rem** [comment]
et aussi avec ceci en PageCSS c'est mieux
```css
#yw-topnav .dropdown-menu li:hover,
#yw-topnav .dropdown-menu li:hover li {
  background-color: var(--neutral-color);
}
```
